### PR TITLE
Global variables are now thread safe

### PR DESCRIPTION
**Pull request by matarc-zz**

### CODE REVIEW

**Comment by soul9** [comment]
could you please rename mutex to erridMu?

**Comment by matarc-zz** [comment]
I don't mind but please notice that this mutex also assures thread safety of MaxStackDepth, do you still want erridMu as a name ?

**Comment by soul9** [comment]
ah ok. nvm.

**Comment by matarc-zz** [comment]
Maybe each should have its own mutex that might actually be a better idea. What do you think ?

**Comment by soul9** [comment]
bah. this is fine.

**Pull request merged**
